export enum FileServerSocketKeys {
  START_VIDEO_UPLOAD = 'START_VIDEO_UPLOAD',
  UPLOAD_VIDEO_STARTED = 'UPLOAD_VIDEO_STARTED',
  UPLOAD_VIDEO_ERROR = 'UPLOAD_VIDEO_ERROR',
  UPLOAD_VIDEO_END = 'UPLOAD_VIDEO_END',
  UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS',
  UPLOAD_VIDEO_CHUNK = 'UPLOAD_VIDEO_CHUNK',
}