export enum GenericFileServerSocketKeys {
  START_UPLOAD = 'START_UPLOAD',
  UPLOAD_STARTED = 'UPLOAD_STARTED',
  UPLOAD_ERROR = 'UPLOAD_ERROR',
  UPLOAD_END = 'UPLOAD_END',
  UPLOAD_SUCCESS = 'UPLOAD_SUCCESS',
  UPLOAD_CHUNK = 'UPLOAD_CHUNK',
}